FROM golang:1.18-alpine AS builder

WORKDIR /app
COPY cms/go.mod cms/go.sum ./
RUN go mod download

COPY cms/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -o cms .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/cms .
COPY --from=builder /app/admin ./admin/

EXPOSE 4000
CMD ["./cms"]